# ==========================
# Kitty - Configuración base
# ==========================

# Fuente (la cambiaremos por una Nerd Font más adelante)
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Historial del terminal
scrollback_lines 10000

# No preguntar al cerrar una ventana
confirm_os_window_close 0

# Copiar automáticamente al seleccionar texto
copy_on_select yes

# Abrir enlaces con Ctrl+Click
open_url_with default

# Sin campana sonora
enable_audio_bell no
visual_bell_duration 0

# Ligera transparencia
background_opacity 0.90

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
